language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - beaker_extensions-0.2.4
    - dogpile.cache-0.5.4.1
    - colander-1.0b3
    - cornice-0.17
    - pyramid_deform-0.2a6
    - eform_bootstrap-3.0.2
    - ntorque
    - pyramid_torque_engine
    - winnow.gi
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install setuptools_git==1.1
  - pip install -r requirements.txt
script:
  - easy_install --version
  - python smile.py
