sudo: false
language: python
python: 2.7
cache: pip
install:
- pip install --upgrade setuptools
- pip install --upgrade pip
- pip install -U pip wheel
- pip install setuptools_git==1.1
script:
- easy_install --version
- python smile.py
